spring:
  datasource:
    url: jdbc:h2:mem:blackpearldev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  flyway:
    enabled: false